### ISSUE TITLE
Need to update version of ISPC

### ISSUE THREAD

**Issue by GregAbram** [TACC/Galaxy#8]
Its pulling 1.9.2 - need 1.11.0 on Mojave

**Comment by jeffamstutz** [comment]
I'd recommend 1.10.0 until a patch release of 1.11 is out fixing an issue related to PIC (see OSPRay issue [here](https://github.com/ospray/ospray/issues/322)).

**Comment by pnav** [comment]
updated to pull ispc v1.10.0 in dev at commit 905344f
